### ISSUE TITLE
Relicense posts to CC BY-SA 4.0

### ISSUE THREAD

**Issue by nickolas360** [Hardmath123/hardmath123.github.io#11]
As previously discussed.

**Comment by SpooikypokDev** [comment]
What are the differences between the different versions of the Creative Commons licenses?

**Comment by bobbybee** [comment]
The -NC and -ND licenses are not free and are thus incompatible with the free culture movement. @nickolas360 knows more about the issue than I do, however.

**Comment by SpooikypokDev** [comment]
The question I'm asking is: what are the differences between the version 3.0 and 4.0?

**Comment by nickolas360** [comment]
You can read about the differences between 3.0 and 4.0 licenses here: <https://creativecommons.org/share-your-work/licensing-considerations/version4/>, but that's not what this issue is about. The posts are currently licensed under CC BY-NC, not CC BY-SA.
