### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by ryanhaney** [Hardmath123/hardmath123.github.io#18]
Recently launched two repos with nearley. Wanted to say thanks, and see if I could get a mention on https://nearley.js.org/.

https://github.com/appology/nearley-template
https://github.com/appology/resp-parser

Thanks again!

Ryan

**Comment by Hardmath123** [comment]
Glad you like nearley! I added resp-parser to the homepage. I don't think nearley-template is really a project that "uses" nearley, though.

Thanks for the submission!

P.S. This issue would probably fit better on the nearley repo itself — that way other maintainers can take care of it if I'm away.

**Comment by ryanhaney** [comment]
Thanks for the mention of resp-parser! Greatly appreciated.
