### ISSUE TITLE
Needs more pizza

### ISSUE THREAD

**Issue by bobbybee** [Hardmath123/hardmath123.github.io#7]
:pizza:

**Comment by Hardmath123** [comment]
Error: Pizza ∉ text-based emoticons.

**Comment by Hardmath123** [comment]
If someone can PR me a "make pizza" button that sends me a pizza everytime an appreciative reader clicks it, I will probably marry them on the spot.

**Comment by bobbybee** [comment]
@Hardmath123 On it!

**Comment by bobbybee** [comment]
Solved in PR #8

**Comment by Hardmath123** [comment]
Merged, neat-o.

Dang, now I'm obligated to marry you on the spot. :P

**Comment by bobbybee** [comment]
Hmm.. the button isn't showing up in the navbar. Any idea what's happening?

**Comment by Hardmath123** [comment]
I slipped it into the footer:

![screen shot 2015-03-19 at 3 59 48 pm](https://cloud.githubusercontent.com/assets/5202416/6742908/141e14a4-ce51-11e4-8fb1-e27090980d54.png)

I thought the header was just a teensy bit conspicuous for an easter egg. :P

**Comment by bobbybee** [comment]
@Hardmath123 Ah, I need to read commit history :D
